### ISSUE TITLE
installation documentation

### ISSUE THREAD

**Issue by Wandang** [zeffii/Blender_CAD_utils#16]
Could you add information how you access the circlecenter functions (hotkeys) like you did for the other functions. For example: Switching into edit modus first, marking several edges/vertices and then using "w" for special menu and so on

Furthermore commenting on this blender-stackexchange answer: http://blender.stackexchange.com/a/28241/12883 : 
It is unclear to me how to get the "circle center from selected" menu. Mainly because I am a noob. Could you elaborate on this?

Thank you very much for your hard work.

**Comment by zeffii** [comment]
**addon installation**

This seems to be a painful experience for most new Blender users, and there are 2 ways to install an addon, but I suggest doing it manually (**do not use "install from file"**).

- make a folder somewhere on your harddrive called "Blender_addons"  or something ( the name of this folder is not so important
- inside this folder make a folder called `scripts`
- inside `scripts` make a folder called `addons` .
- drop the mesh_tinyCAD folder in this `addons` folder
- In the end you have something like `Blender_addons/scripts/addons/mesh_tinyCAD`, which has the various tinyCAD python files.
- inside Blender Preferences go to `File` and change the `scripts` folder to the location of your scripts folder.

![image](https://cloud.githubusercontent.com/assets/619340/7048864/b9380232-de15-11e4-83c7-aebfdb1c9c92.png)

For instance on my machine I have `GITHUB/scripts`  (which itself has an `addons` folder)

- in the Add-ons tab, make sure `Community` is selected and you can narrow down the search by enering 'tiny' into the search area. 
- If you see mesh_tinyCAD then tick it, press Ctrl+U and press the 'Save user settings' 
- The menu will then be visible from W. and the addon is permanently enabled.

**showing menu**

in Edit Mode, with 3 vertices selected, you hit W to show the Specials menu, pick TinyCAD and drop down to the circle centre item as shown in the GIF.  

**showing grease pencil**

I would like to automate this.. but the grease pencil part of Blender is still under development, and that doesn't work at the moment. (probably my mistake)

As shown in the GIF, navigate to the GreasePencil dropdown, and pick `tc_circle_000` (currently hard-coded with that name). The green layer shall be visible then.

**Comment by Wandang** [comment]
Thanks for the fast reply. Unfortunately your explanation was not what I meant in the last part of my question.
I got everything that you explained to work. Only the last step in the gif seems to be a hotkey to get the "circle center from selected"-menu. Sorry if I am missing something obvious here.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7049294/bf42d76c-de18-11e4-9872-ed734e0db235.png)
That's the W key, when in Edit Mode, if the W doesn't show the tinyCAD option it isn't installed properly.

**Comment by zeffii** [comment]
Though I did do a recent update, and removed the panel from the Right Side Toolbar.  You might want to redownload the addon.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7049373/3e92c770-de19-11e4-86d1-44114f337a2b.png)
Another way to launch the operator is by using the spacebar menu, and type in 'center'

**Comment by zeffii** [comment]
The Hotkey to get the operator menu I think you're referring to is `F6` , but it isn't available if you do anything other than 
- starting the operator ( W -> etc)
- selecting  the greasepencil layer
- F6 will still be available.

if you click any other vertices just after starting the operator, the F6 window becomes unavailable because the operator considers that you have finished with the operation.

**Comment by Wandang** [comment]
Sorry for the late reply.

You explained it all. Thank you very much. It worked flawlessly!
