### ISSUE TITLE
I cannot install on Blender 2.74

### ISSUE THREAD

**Issue by kaverdrew** [zeffii/Blender_CAD_utils#21]
![not able to install](https://cloud.githubusercontent.com/assets/12913930/8186533/1484826c-144b-11e5-9b15-52c3d1bde8df.jpg)
I always have this error message: what can I do?
Waiting for an answer.

Thank you.

**Comment by zeffii** [comment]
I think you need to [update your blender](https://builder.blender.org/download/), `mesh_tinyCAD` addon now uses custom icons which are implemented in later versions of 2.74 only.

**Comment by kaverdrew** [comment]
grazie.

**Comment by zeffii** [comment]
though perhaps I should make the custom icons optional (but this would add extra complexity to the code..so not going to happen) I will update the main readme to reflect this new requirement.
