### ISSUE TITLE
Unable to activate the add-on

### ISSUE THREAD

**Issue by Gjfvv** [zeffii/Blender_CAD_utils#22]
When trying to activate the add-on I get this error message:

![error](https://cloud.githubusercontent.com/assets/13078175/8393563/41502a1c-1d15-11e5-8d72-0568ea18451c.jpg)

I use blender 2.74 on a Windows 8.1 pc.

**Comment by zeffii** [comment]
see this: https://github.com/zeffii/Blender_CAD_utils/issues/21  .. same issue, get a newer version of 2.74 or release candidates of 2.75
