### ISSUE TITLE
Bring back EXM

### ISSUE THREAD

**Issue by Aiena-g** [zeffii/Blender_CAD_utils#33]
Hi Zeffi,

Is it possible for you to bring back EXM I know it was an experimental feature but it is really handy. Also I tried the fillet tools mentioned in the Bleder artists posts. But they do not cover the case where if 2 lines do not meet to fillet them so they meet at the intersection. Could you implement that feature ?

Dying to try E2F but afraid that I wont be able to use EXM if I update.

**Comment by Aiena-g** [comment]
Actually this could be a separate tool. As Its an operation between 2 edges or faces. vs EXM which extend mutiple edges to another edge.

I miss the feature of Fillet in other cad software where you can select 2 edges and it will extend each to meet the other.

Actually may be hard in blender because you need a third input of direction too.

But can you at least keep EXM love that feature.

**Comment by zeffii** [comment]
hi @Aiena-g currently my development machine is broken and I don't have time to fix it.

1. I have no problem with adding EXM back. I got so little feedback from tinyCAD users regarding EXM that I won't make it a priority. I also rarely used EXM and don't know how buggy it is.
2. yeah, this is an interesting suggestion. I've been looking at macros (a way to chain operators one after the other) -- i'd called it CHP "Chamfer Plus" 
   - trigger CHP
   - if AutoVTX can intersect two edges then do intersection
   - then invoke the Fillet operator with the new geometry.

**Comment by zeffii** [comment]
I can turn https://github.com/zeffii/Blender_CAD_utils/blob/53b46c9c70f69fca340015960b78df2894f6a7ad/mesh_tinyCAD/EXM.py into it's own addon - that's more likely to happen than adding it back to tinyCAD.

**Comment by zeffii** [comment]
This is the EXM code as an addon..  install as a new addon.

https://github.com/zeffii/mesh_tinyCAD_EXM  

it doesn't interfere with tinyCAD, when enabled you can trigger EXM using `spacebar` and type `EXM`. I could add the EXM to the tinyCAD Specials menu (w) ..

**Comment by zeffii** [comment]
ok. i've added it to the W menu again. Just to be clear EXM is not part of mesh_tinyCAD anymore. it's a separate Add-on now, that attaches itself to the menu that mesh_tinyCAD creates.

**Comment by zeffii** [comment]
https://github.com/zeffii/mesh_tinyCAD_CHP  is ready for testing

**Comment by Aiena-g** [comment]
thanks going to test it
